import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Eye, EyeOff, LockKeyhole, Mail, UserRound } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

function AuthFrame({ children }: { children: React.ReactNode }) { return <main className="relative grid min-h-dvh place-items-center overflow-hidden bg-background p-4"><div className="pointer-events-none absolute -left-28 -top-24 h-96 w-96 rounded-full bg-[radial-gradient(circle,rgba(130,100,255,.28),transparent_66%)] blur-2xl" /><div className="pointer-events-none absolute -bottom-36 -right-24 h-96 w-96 rounded-full bg-[radial-gradient(circle,rgba(101,215,255,.23),transparent_66%)] blur-2xl" /><section className="relative w-full max-w-md rounded-[2rem] border border-border/80 bg-card/90 px-6 py-8 shadow-[0_28px_100px_rgba(51,41,118,.15)] backdrop-blur sm:px-9 sm:py-10"><Link href="/" className="inline-flex items-center gap-2 font-semibold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-[14px] bg-[linear-gradient(135deg,#6049ea,#a177ff_55%,#67d3ff)] text-sm font-black text-white shadow-[0_8px_22px_rgba(99,91,255,.28)]">N</span>nuvora</Link>{children}</section></main>; }
function PasswordInput({ value, onChange, autoComplete = "current-password" }: { value: string; onChange: (value: string) => void; autoComplete?: string }) { const [visible, setVisible] = useState(false); return <div className="relative"><Input value={value} onChange={event => onChange(event.target.value)} type={visible ? "text" : "password"} autoComplete={autoComplete} className="h-12 rounded-xl pr-12" required /><button type="button" className="absolute right-1 top-1 grid h-10 w-10 place-items-center rounded-lg text-muted-foreground hover:bg-accent hover:text-foreground" onClick={() => setVisible(!visible)} aria-label={visible ? "Hide password" : "Show password"}>{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button></div>; }
export function SignUp() { const [, navigate] = useLocation(); const utils = trpc.useUtils(); const register = trpc.auth.local.register.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); navigate("/onboarding", { replace: true }); }, onError: error => toast.error(error.message) }); const [displayName, setDisplayName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); return <AuthFrame><div className="mt-8"><p className="eyebrow">Create your account</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Start with a real profile.</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Your account keeps your posts, conversations, privacy settings, and saved content connected to you.</p><form className="mt-7 space-y-4" onSubmit={event => { event.preventDefault(); register.mutate({ displayName, email, password }); }}><label className="block text-sm font-semibold">Name<Input className="mt-2 h-12 rounded-xl" value={displayName} onChange={event => setDisplayName(event.target.value)} autoComplete="name" placeholder="Your name" required /></label><label className="block text-sm font-semibold">Email<Input className="mt-2 h-12 rounded-xl" type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" placeholder="you@example.com" required /></label><label className="block text-sm font-semibold">Password<PasswordInput value={password} onChange={setPassword} autoComplete="new-password" /><span className="mt-2 block text-xs font-normal text-muted-foreground">Use 12+ characters with at least one letter and one number.</span></label><Button type="submit" className="mt-2 h-12 w-full rounded-xl" disabled={register.isPending}>{register.isPending ? "Creating account…" : "Create account"}</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">Already have an account? <Link href="/login" className="font-semibold text-primary hover:underline">Log in</Link></p></div></AuthFrame>; }
export function Login() { const [, navigate] = useLocation(); const utils = trpc.useUtils(); const signIn = trpc.auth.local.signIn.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); navigate("/", { replace: true }); }, onError: () => toast.error("Email or password is incorrect.") }); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); return <AuthFrame><div className="mt-8"><p className="eyebrow">Welcome back</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Log in to your space.</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Everything you have shared and saved stays connected to your account.</p><form className="mt-7 space-y-4" onSubmit={event => { event.preventDefault(); signIn.mutate({ email, password }); }}><label className="block text-sm font-semibold">Email<Input className="mt-2 h-12 rounded-xl" type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" placeholder="you@example.com" required /></label><label className="block text-sm font-semibold">Password<PasswordInput value={password} onChange={setPassword} /></label><div className="flex justify-end"><Link href="/account-help" className="text-xs font-semibold text-primary hover:underline">Need help signing in?</Link></div><Button type="submit" className="h-12 w-full rounded-xl" disabled={signIn.isPending}>{signIn.isPending ? "Logging in…" : "Log in"}</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">New to nuvora? <Link href="/signup" className="font-semibold text-primary hover:underline">Create an account</Link></p></div></AuthFrame>; }
export function AccountHelp() { return <AuthFrame><div className="mt-8 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><LockKeyhole size={22} /></span><h1 className="mt-6 text-2xl font-semibold tracking-tight">Account help is kept private.</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Password reset email delivery must be configured before it can be offered safely. Use your connected account option if that is how you created your account, or contact the workspace administrator for recovery support.</p><div className="mt-7 grid gap-3"><Link href="/login"><Button className="w-full rounded-xl">Back to log in</Button></Link><Link href="/signup"><Button variant="outline" className="w-full rounded-xl">Create a new account</Button></Link></div></div></AuthFrame>; }
