import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Compass, Info, Plus, UsersRound } from "lucide-react";
import { Link } from "wouter";

export default function Communities() {
  return <AppShell><section className="mx-auto max-w-5xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Shared spaces</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.05em] sm:text-4xl">Communities</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Find a shared space when a conversation needs more room than a group chat.</p></div><Button variant="outline" className="rounded-xl" disabled title="Community creation is not enabled in this deployment"><Plus size={16} />Create community</Button></div><section className="surface-panel mt-7 overflow-hidden"><div className="border-b border-border bg-primary/[.06] px-6 py-6 sm:px-8"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-primary text-primary-foreground"><UsersRound size={21} /></span><div><h2 className="font-display text-lg font-semibold">A home for ongoing conversations</h2><p className="mt-1 max-w-lg text-sm leading-6 text-muted-foreground">Communities will bring groups, announcement channels, and member information together without competing with your private chats.</p></div></div></div><div className="grid gap-4 p-6 sm:grid-cols-3 sm:p-8"><CommunityPrinciple icon={Compass} title="Discover" text="Find spaces by topic when the directory is connected." /><CommunityPrinciple icon={UsersRound} title="Join" text="See groups and channels from one community home." /><CommunityPrinciple icon={Info} title="Stay informed" text="Read announcements without losing your personal inbox." /></div><div className="border-t border-border px-6 py-5 sm:px-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">No communities available yet</p><p className="mt-1 text-xs text-muted-foreground">This workspace has not published a community directory.</p></div><Link href="/messages"><Button className="rounded-xl">Return to chats</Button></Link></div></div></section></section></AppShell>;
}

function CommunityPrinciple({ icon: Icon, title, text }: { icon: typeof Compass; title: string; text: string }) {
  return <article className="rounded-2xl border border-border bg-background p-4"><Icon size={18} className="text-primary" /><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-1.5 text-xs leading-5 text-muted-foreground">{text}</p></article>;
}
