import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { PostCard, type FeedPost } from "@/components/PostCard";
import { PostComposer } from "@/components/PostComposer";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, Clapperboard, LockKeyhole, MessageCircleMore, Plus, Sparkles, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";

/**
 * All content in this page are only for example, replace with your own feature implementation
 * When building pages, remember your instructions in Frontend Workflow, Frontend Best Practices, Design Guide and Common Pitfalls
 */
export default function Home() {
  const { isAuthenticated } = useAuth();
  const account = trpc.account.me.useQuery(undefined, { enabled: isAuthenticated });
  const [, navigate] = useLocation();
  useEffect(() => { if (isAuthenticated && account.data && !account.data.profile.onboardingCompletedAt) navigate("/onboarding", { replace: true }); }, [isAuthenticated, account.data?.profile.onboardingCompletedAt, navigate]);
  return <AppShell>{isAuthenticated ? <SignedInHome /> : <WelcomeHome />}</AppShell>;
}

function WelcomeHome() {
  return <div className="mx-auto flex min-h-[calc(100dvh-11rem)] max-w-md items-center"><section className="relative w-full overflow-hidden rounded-[2rem] border border-border bg-card px-7 py-11 text-center shadow-[0_24px_80px_rgba(42,34,104,.10)] sm:px-10"><div className="pointer-events-none absolute -right-16 -top-16 h-48 w-48 rounded-full bg-[radial-gradient(circle,rgba(101,215,255,.42),rgba(99,91,255,.06)_56%,transparent_72%)] blur-xl" /><span className="relative mx-auto grid h-16 w-16 place-items-center rounded-[23px] bg-[linear-gradient(135deg,#6049ea,#a177ff_55%,#67d3ff)] text-2xl font-black text-white shadow-[0_12px_30px_rgba(99,91,255,.3)]">L</span><div className="relative"><p className="eyebrow mt-7">Social, in a softer light</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em]">A place for the people and moments that matter.</h1><p className="mt-5 text-sm leading-6 text-muted-foreground">Share your perspective, discover thoughtful voices, and keep conversations close.</p><div className="mt-8 grid gap-3"><Button className="h-12 rounded-xl text-base" onClick={startLogin}>Create account <ArrowUpRight size={17} /></Button><Button variant="outline" className="h-12 rounded-xl text-base" onClick={startLogin}>Log in</Button></div><p className="mt-5 text-xs leading-5 text-muted-foreground">Sign in securely with the configured account provider. Additional social providers appear only when configured.</p></div></section></div>;
}

function SignedInHome() {
  const [page, setPage] = useState(0);
  const [loadedPosts, setLoadedPosts] = useState<FeedPost[]>([]);
  const feedInput = useMemo(() => ({ page, pageSize: 10 }), [page]);
  const videoInput = useMemo(() => ({ page: 0, pageSize: 3 }), []);
  const feed = trpc.social.feed.useQuery(feedInput);
  const storyFeed = trpc.stories.list.useQuery();
  const videoFeed = trpc.videos.list.useQuery(videoInput);
  useEffect(() => { if (feed.data) setLoadedPosts(current => page === 0 ? feed.data as FeedPost[] : [...current, ...(feed.data as FeedPost[])].filter((post, index, all) => all.findIndex(item => item.publicId === post.publicId) === index)); }, [feed.data, page]);
  const reloadFeed = () => { setLoadedPosts([]); setPage(0); void feed.refetch(); };
  const hasMore = (feed.data?.length ?? 0) === 10;
  return <div className="mx-auto grid max-w-5xl gap-7 lg:grid-cols-[minmax(0,1fr)_240px]"><div className="space-y-5"><StoryStrip rows={storyFeed.data ?? []} /><HomeVideoRail rows={videoFeed.data ?? []} /><PostComposer onPublished={reloadFeed} />{feed.isLoading && page === 0 ? <FeedSkeleton /> : feed.isError && page === 0 ? <section className="surface-panel px-6 py-10 text-center"><h1 className="font-semibold">We couldn’t reach your feed.</h1><Button variant="outline" className="mt-5 rounded-full" onClick={() => feed.refetch()}>Try again</Button></section> : loadedPosts.length ? <>{loadedPosts.map(post => <PostCard key={post.publicId} post={post} signedIn onMutate={reloadFeed} />)}{hasMore && <div className="pt-1 text-center"><Button variant="outline" className="rounded-full" disabled={feed.isFetching} onClick={() => setPage(current => current + 1)}>{feed.isFetching ? "Loading…" : "Load more"}</Button></div>}</> : <section className="surface-panel px-6 py-12 text-center sm:px-10"><UsersRound className="mx-auto h-7 w-7 text-primary" /><p className="eyebrow mt-5">Your feed</p><h1 className="mt-3 text-2xl font-semibold tracking-tight">Your community is ready to take shape.</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">Find people and topics you like, or publish a moment to begin tailoring Luma around you.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link href="/explore" className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90">Find people <ArrowUpRight size={16} /></Link><Link href="/create" className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-5 py-2.5 text-sm font-semibold transition hover:bg-accent">Create something <Plus size={16} /></Link></div></section>}</div><aside className="hidden lg:block"><section className="sticky top-24 surface-panel p-5"><p className="eyebrow">Built for your pace</p><h2 className="mt-3 text-lg font-semibold tracking-tight">A more intentional social space.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Share in your own time. Luma keeps privacy controls and meaningful conversations close at hand.</p><Link href="/reels" className="mt-5 flex items-center justify-between rounded-2xl bg-primary/8 p-3 text-sm font-semibold text-primary transition hover:bg-primary/12">Discover short videos <Clapperboard size={18} /></Link></section></aside></div>;
}

function HomeVideoRail({ rows }: { rows: Array<{ publicId: string; posterUrl: string | null; caption: string | null; author: { displayName: string } }> }) { return <section className="surface-panel overflow-hidden"><div className="flex items-center justify-between px-5 pb-3 pt-4"><div><p className="text-sm font-semibold">Short videos</p><p className="mt-0.5 text-xs text-muted-foreground">Fresh perspectives, made for a quick watch.</p></div><Link href="/reels" className="text-xs font-semibold text-primary">Watch all</Link></div>{rows.length ? <div className="flex gap-3 overflow-x-auto px-5 pb-4 [scrollbar-width:none]">{rows.map(video => <Link href="/reels" key={video.publicId} className="relative h-34 w-25 shrink-0 overflow-hidden rounded-2xl bg-secondary"><img src={video.posterUrl ?? ""} alt="" className="h-full w-full object-cover" /><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent px-2 pb-2 pt-8 text-[10px] font-semibold text-white">{video.caption || video.author.displayName}</span></Link>)}</div> : <Link href="/reels" className="flex items-center justify-between bg-primary/[.04] px-5 py-3 text-sm text-muted-foreground transition hover:bg-primary/[.08]"><span>Short videos are ready when you are.</span><span className="font-semibold text-primary">Open videos <Clapperboard className="ml-1 inline" size={15} /></span></Link>}</section>; }

function StoryStrip({ rows }: { rows: Array<{ story: { publicId: string; url: string; kind: string }; author: { displayName: string; username: string; avatarUrl: string | null } }> }) { return <section className="surface-panel overflow-hidden py-4"><div className="flex items-start gap-4 overflow-x-auto px-4 pb-1 [scrollbar-width:none]"><Link href="/stories" className="group flex w-17 shrink-0 flex-col items-center gap-2 text-center"><span className="relative grid h-16 w-16 place-items-center rounded-full border-2 border-dashed border-primary/60 bg-primary/6 text-primary transition group-hover:bg-primary group-hover:text-primary-foreground"><Plus size={21} /><span className="absolute -bottom-1 -right-1 grid h-5 w-5 place-items-center rounded-full border-2 border-card bg-foreground text-card text-[11px]">+</span></span><span className="w-full truncate text-[11px] font-medium">Your story</span></Link>{rows.slice(0, 12).map(({ story, author }) => <Link href="/stories" key={story.publicId} className="group flex w-17 shrink-0 flex-col items-center gap-2 text-center"><span className="rounded-full bg-[conic-gradient(from_40deg,#65d7ff,#635bff,#c17bff,#65d7ff)] p-0.5"><span className="grid h-15 w-15 place-items-center overflow-hidden rounded-full border-2 border-card bg-secondary text-lg font-semibold text-secondary-foreground">{author.avatarUrl ? <img src={author.avatarUrl} className="h-full w-full object-cover" alt="" /> : author.displayName.slice(0,1).toUpperCase()}</span></span><span className="w-full truncate text-[11px] font-medium">{author.username}</span></Link>)}</div>{!rows.length && <p className="px-4 pt-3 text-xs text-muted-foreground">Stories disappear after 24 hours. Add yours to share a quick update.</p>}</section>; }

function FeedSkeleton() { return <div className="space-y-5">{[0, 1].map(item => <div className="surface-panel animate-pulse p-5" key={item}><div className="h-10 w-40 rounded-xl bg-muted" /><div className="mt-4 aspect-square rounded-2xl bg-muted" /><div className="mt-4 h-4 w-2/3 rounded bg-muted" /></div>)}</div>; }

function ValueCard({ icon: Icon, title, text }: { icon: typeof Sparkles; title: string; text: string }) { return <article className="surface-panel px-5 py-6"><Icon size={20} className="text-primary" /><h2 className="mt-5 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>; }
