import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { AudioLines, ArrowLeft, CheckCheck, FileUp, Forward, Loader2, MessageCircleMore, Mic, Paperclip, Plus, Search, Send, SmilePlus, Trash2, UsersRound, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";

 type Conversation = { publicId: string; kind: "direct" | "group"; title: string | null; description?: string | null; role: "member" | "admin" | "owner"; lastMessageAt: Date | null; lastMessage: { body: string | null; kind: string; createdAt: Date } | null; members: Array<{ userId: number; role: string; profile: { displayName: string; username: string; avatarUrl: string | null }; lastSeenAt: Date | null }> };
 type ChatMessage = { id: number; publicId: string; senderId: number; kind: "text" | "image" | "video" | "audio" | "file" | "system"; body: string | null; replyToId: number | null; forwardedFromId: number | null; deletedAt: Date | null; createdAt: Date; sender: { displayName: string; username: string; avatarUrl: string | null }; attachments: Array<{ id: number; kind: "image" | "video" | "audio" | "file"; url: string; originalName: string; mimeType: string }>; reactions: Array<{ userId: number; emoji: string }>; readBy: number[]; deliveredTo: number[] };

type Filter = "all" | "unread" | "groups" | "favorites";

export default function Messages() {
  const { isAuthenticated, user } = useAuth();
  const conversations = trpc.messages.listConversations.useQuery(undefined, { enabled: isAuthenticated, refetchInterval: 5000 });
  const [activeId, setActiveId] = useState<string | null>(null);
  const [newChatOpen, setNewChatOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<Filter>("all");
  const [favorites, setFavorites] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("nuvora-favorite-chats") || "[]"); } catch { return []; } });
  useEffect(() => { if (!activeId && conversations.data?.[0]) setActiveId(conversations.data[0].publicId); }, [activeId, conversations.data]);
  const toggleFavorite = (id: string) => setFavorites(current => { const next = current.includes(id) ? current.filter(item => item !== id) : [...current, id]; try { localStorage.setItem("nuvora-favorite-chats", JSON.stringify(next)); } catch {} return next; });
  if (!isAuthenticated) return <AppShell><section className="surface-panel mx-auto max-w-lg px-6 py-14 text-center"><MessageCircleMore className="mx-auto text-primary" size={30} /><p className="eyebrow mt-5">Private conversations</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Sign in to open your chats.</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Your conversations, groups, and shared moments belong in one protected space.</p><Button className="mt-6 rounded-xl" onClick={startLogin}>Sign in to messages</Button></section></AppShell>;
  const data = (conversations.data ?? []) as Conversation[];
  const filtered = data.filter(chat => { const label = conversationName(chat, user?.id); const matchesSearch = !search.trim() || `${label} ${chat.lastMessage?.body || ""}`.toLowerCase().includes(search.trim().toLowerCase()); const matchesFilter = filter === "all" || (filter === "groups" && chat.kind === "group") || (filter === "favorites" && favorites.includes(chat.publicId)) || (filter === "unread" && false); return matchesSearch && matchesFilter; });
  const active = data.find(chat => chat.publicId === activeId) ?? null;
  return <AppShell><section className="mx-auto max-w-7xl"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your communication space</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.05em] sm:text-4xl">Chats</h1><p className="mt-2 text-sm text-muted-foreground">Stay close to the people and groups that matter.</p></div><Button className="rounded-xl" onClick={() => setNewChatOpen(true)}><Plus size={16} />New chat</Button></div>{newChatOpen && <NewConversation onClose={() => setNewChatOpen(false)} onCreated={id => { setNewChatOpen(false); setActiveId(id); void conversations.refetch(); }} />}<div className="surface-panel overflow-hidden lg:grid lg:min-h-[min(720px,calc(100dvh-13rem))] lg:grid-cols-[minmax(18rem,22rem)_minmax(0,1fr)]"><div className={activeId ? "hidden lg:block" : "block"}><ConversationList data={filtered} allCount={data.length} currentUserId={user?.id ?? 0} selectedId={activeId} onSelect={setActiveId} loading={conversations.isLoading} search={search} onSearch={setSearch} filter={filter} onFilter={setFilter} favorites={favorites} onToggleFavorite={toggleFavorite} /></div><div className={activeId ? "block" : "hidden lg:block"}>{active && user ? <ConversationPanel conversation={active} currentUserId={user.id} onBack={() => setActiveId(null)} onConversationChange={() => void conversations.refetch()} /> : <div className="grid min-h-[26rem] place-items-center p-8 text-center"><div><MessageCircleMore className="mx-auto text-primary" size={28} /><h2 className="mt-4 text-lg font-semibold">Choose a conversation.</h2><p className="mt-2 max-w-xs text-sm leading-6 text-muted-foreground">Select a chat from your inbox or start a new one with a username.</p></div></div>}</div></div></section></AppShell>;
}

function ConversationList({ data, allCount, currentUserId, selectedId, onSelect, loading, search, onSearch, filter, onFilter, favorites, onToggleFavorite }: { data: Conversation[]; allCount: number; currentUserId: number; selectedId: string | null; onSelect: (id: string) => void; loading: boolean; search: string; onSearch: (value: string) => void; filter: Filter; onFilter: (value: Filter) => void; favorites: string[]; onToggleFavorite: (id: string) => void }) {
  const filters: Array<{ id: Filter; label: string }> = [{ id: "all", label: `All ${allCount ? `· ${allCount}` : ""}` }, { id: "unread", label: "Unread" }, { id: "groups", label: "Groups" }, { id: "favorites", label: "Favorites" }];
  return <aside className="flex min-h-[26rem] flex-col border-b border-border bg-card lg:border-b-0 lg:border-r"><div className="border-b border-border px-4 pb-4 pt-4 sm:px-5"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={event => onSearch(event.target.value)} placeholder="Search chats" aria-label="Search chats" className="h-10 rounded-xl bg-background pl-9" /></div><div className="mt-3 flex gap-1 overflow-x-auto [scrollbar-width:none]">{filters.map(item => <button key={item.id} type="button" onClick={() => onFilter(item.id)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-semibold transition ${filter === item.id ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground hover:bg-accent hover:text-foreground"}`}>{item.label}</button>)}</div></div><div className="flex-1 overflow-y-auto p-2">{loading ? <ConversationSkeleton /> : data.length ? data.map(chat => <ConversationRow key={chat.publicId} chat={chat} currentUserId={currentUserId} selected={selectedId === chat.publicId} favorite={favorites.includes(chat.publicId)} onSelect={onSelect} onToggleFavorite={onToggleFavorite} />) : <div className="px-4 py-12 text-center"><MessageCircleMore className="mx-auto text-primary" size={24} /><h2 className="mt-4 text-sm font-semibold">You don’t have any conversations yet.</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Start a new chat to make this space yours.</p><Button size="sm" className="mt-5 rounded-lg" onClick={() => onFilter("all")}>Start a new chat</Button></div>}</div></aside>;
}

function ConversationRow({ chat, currentUserId, selected, favorite, onSelect, onToggleFavorite }: { chat: Conversation; currentUserId: number; selected: boolean; favorite: boolean; onSelect: (id: string) => void; onToggleFavorite: (id: string) => void }) {
  const label = conversationName(chat, currentUserId);
  const last = chat.lastMessage;
  const preview = last?.body || (last ? `Sent a ${last.kind}` : "No messages yet");
  return <div className={`group flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition ${selected ? "bg-primary text-primary-foreground" : "hover:bg-accent"}`}><button type="button" onClick={() => onSelect(chat.publicId)} className="flex min-w-0 flex-1 items-center gap-3 text-left"><Avatar name={label} avatarUrl={chat.kind === "direct" ? chat.members.find(member => member.userId !== currentUserId)?.profile.avatarUrl : undefined} /><span className="min-w-0 flex-1"><span className="flex items-center gap-1.5"><span className="block truncate text-sm font-semibold">{label}</span>{chat.kind === "group" && <UsersRound size={12} className={selected ? "text-primary-foreground/75" : "text-primary"} />}</span><span className={`mt-0.5 block truncate text-xs ${selected ? "text-primary-foreground/75" : "text-muted-foreground"}`}>{preview}</span></span></button><span className="flex shrink-0 flex-col items-end gap-1 self-stretch"><span className={`text-[10px] ${selected ? "text-primary-foreground/70" : "text-muted-foreground"}`}>{last ? formatTime(last.createdAt) : ""}</span><button type="button" onClick={() => onToggleFavorite(chat.publicId)} className={`grid h-6 w-6 place-items-center rounded-full text-xs transition ${favorite ? selected ? "text-primary-foreground" : "text-primary" : "text-transparent group-hover:text-muted-foreground"}`} aria-label={favorite ? `Remove ${label} from favorites` : `Add ${label} to favorites`}>★</button></span></div>;
}

function ConversationPanel({ conversation, currentUserId, onBack, onConversationChange }: { conversation: Conversation; currentUserId: number; onBack: () => void; onConversationChange: () => void }) {
  const input = useMemo(() => ({ conversationId: conversation.publicId, page: 0, pageSize: 50 }), [conversation.publicId]);
  const chat = trpc.messages.listMessages.useQuery(input, { refetchInterval: 3000 });
  const typing = trpc.messages.typingMembers.useQuery({ conversationId: conversation.publicId }, { refetchInterval: 2000 });
  const markRead = trpc.messages.markRead.useMutation();
  const [membersOpen, setMembersOpen] = useState(false);
  const [replyTo, setReplyTo] = useState<ChatMessage | null>(null);
  useEffect(() => { const last = chat.data?.[chat.data.length - 1]; if (last && last.senderId !== currentUserId) markRead.mutate({ conversationId: conversation.publicId, messageId: last.publicId }); }, [chat.data?.[chat.data.length - 1]?.publicId, conversation.publicId]);
  const membersTyping = typing.data?.map(item => item.profile.displayName).join(", ");
  return <div className="flex min-h-[30rem] flex-col lg:h-full"><header className="flex items-center justify-between gap-3 border-b border-border px-4 py-3 sm:px-5"><div className="flex min-w-0 items-center gap-3"><button type="button" onClick={onBack} className="grid h-9 w-9 shrink-0 place-items-center rounded-full text-muted-foreground hover:bg-accent hover:text-foreground lg:hidden" aria-label="Back to chats"><ArrowLeft size={18} /></button><Avatar name={conversationName(conversation, currentUserId)} /><div className="min-w-0"><h2 className="truncate font-semibold">{conversationName(conversation, currentUserId)}</h2><p className="truncate text-xs text-muted-foreground">{conversation.kind === "group" ? `${conversation.members.length} members · ${conversation.description || "Private group"}` : directPresence(conversation, currentUserId)}</p></div></div><div className="flex items-center gap-1"><button type="button" className="grid h-9 w-9 place-items-center rounded-full text-muted-foreground hover:bg-accent hover:text-foreground" aria-label="Search this conversation" onClick={() => toast.info("In-chat search will appear here once the message index is enabled.")}><Search size={17} /></button>{conversation.kind === "group" && <button type="button" onClick={() => setMembersOpen(open => !open)} className="rounded-full bg-secondary px-3 py-1.5 text-xs font-semibold text-secondary-foreground">{conversation.role === "owner" ? "Owner" : conversation.role === "admin" ? "Admin" : "Members"}</button>}</div></header>{membersOpen && <GroupMembers conversation={conversation} canManage={conversation.role === "owner" || conversation.role === "admin"} onChange={onConversationChange} />}<div className="flex-1 space-y-3 overflow-y-auto bg-background/55 p-4 sm:p-5">{chat.isLoading ? <div className="grid min-h-[24rem] place-items-center"><Loader2 className="animate-spin text-primary" /></div> : chat.data?.length ? chat.data.map(message => <MessageBubble key={message.publicId} message={message as ChatMessage} own={message.senderId === currentUserId} conversationId={conversation.publicId} onReply={() => setReplyTo(message as ChatMessage)} onChange={() => void chat.refetch()} />) : <div className="grid min-h-[24rem] place-items-center text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><MessageCircleMore size={22} /></span><p className="mt-4 text-sm font-semibold">No messages yet.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">A thoughtful hello is a good place to start.</p></div></div>}</div>{membersTyping && <p className="px-5 pb-1 text-xs italic text-muted-foreground">{membersTyping} {typing.data?.length === 1 ? "is" : "are"} typing…</p>}<MessageComposer conversationId={conversation.publicId} replyTo={replyTo} onCancelReply={() => setReplyTo(null)} onSent={() => { setReplyTo(null); void chat.refetch(); }} /></div>;
}

function GroupMembers({ conversation, canManage, onChange }: { conversation: Conversation; canManage: boolean; onChange: () => void }) {
  const [username, setUsername] = useState("");
  const add = trpc.messages.addMember.useMutation({ onSuccess: () => { setUsername(""); onChange(); toast.success("Member added to the group."); }, onError: error => toast.error(error.message) });
  const remove = trpc.messages.removeMember.useMutation({ onSuccess: () => { onChange(); toast.success("Member removed from the group."); }, onError: error => toast.error(error.message) });
  const leave = trpc.messages.leave.useMutation({ onSuccess: () => { onChange(); toast.success("You left the group."); }, onError: error => toast.error(error.message) });
  return <section className="border-b border-border bg-muted/40 px-4 py-4 sm:px-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold">Group members</h3><p className="mt-1 text-xs text-muted-foreground">{conversation.members.map(member => `@${member.profile.username}`).join(", ")}</p></div>{conversation.role !== "owner" && <Button variant="outline" size="sm" className="rounded-full" disabled={leave.isPending} onClick={() => leave.mutate({ conversationId: conversation.publicId })}>Leave group</Button>}</div>{canManage && <form className="mt-3 flex gap-2" onSubmit={event => { event.preventDefault(); if (username.trim()) add.mutate({ conversationId: conversation.publicId, username: username.trim().toLowerCase() }); }}><Input value={username} onChange={event => setUsername(event.target.value)} placeholder="Add member by username" aria-label="Add group member" /><Button type="submit" size="sm" className="rounded-full" disabled={add.isPending}>Add</Button></form>}<div className="mt-3 flex flex-wrap gap-2">{canManage && conversation.members.filter(member => member.role !== "owner").map(member => <button type="button" key={member.userId} className="rounded-full bg-card px-3 py-1.5 text-xs font-medium text-muted-foreground hover:text-destructive" onClick={() => remove.mutate({ conversationId: conversation.publicId, username: member.profile.username })}>Remove @{member.profile.username}</button>)}</div></section>;
}

function MessageBubble({ message, own, conversationId, onReply, onChange }: { message: ChatMessage; own: boolean; conversationId: string; onReply: () => void; onChange: () => void }) {
  const reaction = trpc.messages.toggleReaction.useMutation({ onSuccess: onChange });
  const remove = trpc.messages.deleteMessage.useMutation({ onSuccess: onChange });
  const forward = trpc.messages.send.useMutation({ onSuccess: () => toast.success("Forwarded to the current conversation.") });
  const [tools, setTools] = useState(false);
  if (message.deletedAt) return <div className={`flex ${own ? "justify-end" : "justify-start"}`}><p className="rounded-2xl bg-muted px-3 py-2 text-xs italic text-muted-foreground">This message was deleted.</p></div>;
  return <div className={`group flex ${own ? "justify-end" : "justify-start"}`}><div className={`max-w-[86%] rounded-[1.2rem] px-3.5 py-3 shadow-sm ${own ? "rounded-br-md bg-primary text-primary-foreground" : "rounded-bl-md bg-card"}`}><p className={`mb-1 text-[0.68rem] font-semibold ${own ? "text-primary-foreground/75" : "text-muted-foreground"}`}>{own ? "You" : message.sender.displayName}</p>{message.replyToId && <p className={`mb-2 border-l-2 pl-2 text-[0.68rem] italic ${own ? "border-primary-foreground/50 text-primary-foreground/75" : "border-primary/50 text-muted-foreground"}`}>Replying to a message</p>}{message.forwardedFromId && <p className={`mb-1 text-[0.68rem] italic ${own ? "text-primary-foreground/70" : "text-muted-foreground"}`}>Forwarded</p>}{message.body && <p className="whitespace-pre-wrap text-sm leading-6">{message.body}</p>}{message.attachments.map(asset => <AttachmentView key={asset.id} asset={asset} />)}<div className="mt-1.5 flex items-center justify-between gap-3"><p className={`text-[0.62rem] ${own ? "text-primary-foreground/65" : "text-muted-foreground"}`}>{formatTime(message.createdAt)}{own && message.readBy.length ? " · Read" : own && message.deliveredTo.length ? " · Delivered" : own ? " · Sent" : ""}</p><div className="flex items-center gap-1"><button type="button" onClick={onReply} className={`rounded-full p-1 opacity-60 transition hover:opacity-100 ${own ? "text-primary-foreground" : "text-muted-foreground"}`} aria-label="Reply to message"><Forward size={14} className="rotate-180" /></button><button type="button" onClick={() => setTools(open => !open)} className={`rounded-full p-1 opacity-60 transition hover:opacity-100 ${own ? "text-primary-foreground" : "text-muted-foreground"}`} aria-label="Message actions"><SmilePlus size={14} /></button></div></div>{message.reactions.length > 0 && <div className="mt-2 flex flex-wrap gap-1">{Array.from(new Set(message.reactions.map(item => item.emoji))).map(emoji => <button type="button" key={emoji} onClick={() => reaction.mutate({ messageId: message.publicId, emoji })} className="rounded-full bg-background/70 px-2 py-0.5 text-xs text-foreground">{emoji} {message.reactions.filter(item => item.emoji === emoji).length}</button>)}</div>}{tools && <div className="mt-2 flex flex-wrap gap-1 border-t border-current/15 pt-2"><button type="button" className="rounded-lg bg-background/25 px-2 py-1 text-xs" onClick={() => reaction.mutate({ messageId: message.publicId, emoji: "♥" })}>React</button><button type="button" className="rounded-lg bg-background/25 px-2 py-1 text-xs" onClick={() => forward.mutate({ conversationId, forwardedFromId: message.publicId })}><Forward size={12} className="mr-1 inline" />Forward</button>{own && <button type="button" className="rounded-lg bg-background/25 px-2 py-1 text-xs" onClick={() => remove.mutate({ messageId: message.publicId })}><Trash2 size={12} className="mr-1 inline" />Delete</button>}</div>}</div></div>;
}

function AttachmentView({ asset }: { asset: ChatMessage["attachments"][number] }) { if (asset.kind === "image") return <img src={asset.url} alt={asset.originalName} loading="lazy" className="mt-2 max-h-64 rounded-xl object-cover" />; if (asset.kind === "video") return <video src={asset.url} controls preload="metadata" className="mt-2 max-h-64 rounded-xl" />; if (asset.kind === "audio") return <audio src={asset.url} controls className="mt-2 max-w-full" />; return <a href={asset.url} target="_blank" rel="noreferrer" className="mt-2 inline-flex max-w-full items-center gap-1 rounded-lg bg-background/25 px-2 py-1 text-xs underline"><FileUp size={12} />{asset.originalName}</a>; }

function MessageComposer({ conversationId, replyTo, onCancelReply, onSent }: { conversationId: string; replyTo: ChatMessage | null; onCancelReply: () => void; onSent: () => void }) {
  const [body, setBody] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [recording, setRecording] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  const recorder = useRef<MediaRecorder | null>(null);
  const chunks = useRef<Blob[]>([]);
  const upload = trpc.uploads.create.useMutation();
  const send = trpc.messages.send.useMutation({ onSuccess: () => { setBody(""); setFile(null); onSent(); } });
  const typing = trpc.messages.typing.useMutation();
  const busy = upload.isPending || send.isPending;
  const base64For = (item: Blob) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("Attachment could not be read.")); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.readAsDataURL(item); });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!body.trim() && !file) return; try { const uploadIds: string[] = []; if (file) { const purpose = file.type.startsWith("audio/") ? "voice" : "message"; const asset = await upload.mutateAsync({ purpose, originalName: file.name, mimeType: file.type || "application/octet-stream", dataBase64: await base64For(file) }); uploadIds.push(asset.publicId); } await send.mutateAsync({ conversationId, body: body.trim() || null, uploadIds, replyToId: replyTo?.publicId ?? null }); } catch (error) { toast.error(error instanceof Error ? error.message : "Couldn’t send the message. Please retry."); } };
  const startRecording = async () => { if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") return toast.info("Voice recording is not supported in this browser."); try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const active = new MediaRecorder(stream); chunks.current = []; active.ondataavailable = event => chunks.current.push(event.data); active.onstop = () => { const blob = new Blob(chunks.current, { type: active.mimeType || "audio/webm" }); setFile(new File([blob], `voice-note-${Date.now()}.webm`, { type: blob.type })); stream.getTracks().forEach(track => track.stop()); }; active.start(); recorder.current = active; setRecording(true); } catch { toast.error("Microphone permission is required to record a voice note."); } };
  const stopRecording = () => { recorder.current?.stop(); setRecording(false); };
  return <form onSubmit={submit} className="border-t border-border bg-card p-3 sm:p-4"><input ref={input} type="file" className="sr-only" accept="image/*,video/*,audio/*,.pdf,.txt,.doc,.docx" onChange={event => setFile(event.target.files?.[0] ?? null)} /><div className="flex items-center gap-2"><Button type="button" variant="ghost" size="icon" className="shrink-0 rounded-full" onClick={() => input.current?.click()} aria-label="Attach a photo, video, audio, or file"><Paperclip size={18} /></Button><Input value={body} onChange={event => { setBody(event.target.value); typing.mutate({ conversationId, active: event.target.value.length > 0 }); }} onBlur={() => typing.mutate({ conversationId, active: false })} maxLength={8000} placeholder="Write a message…" aria-label="Message text" className="h-11 rounded-xl bg-background" /><Button type="button" variant={recording ? "destructive" : "ghost"} size="icon" className="shrink-0 rounded-full" onClick={recording ? stopRecording : startRecording} aria-label={recording ? "Stop recording" : "Record voice note"}>{recording ? <AudioLines size={18} /> : <Mic size={18} />}</Button><Button type="submit" size="icon" className="shrink-0 rounded-xl" disabled={busy || (!body.trim() && !file)} aria-label="Send message">{busy ? <Loader2 className="animate-spin" size={17} /> : <Send size={17} />}</Button></div>{replyTo && <div className="mt-2 flex items-center justify-between rounded-xl bg-primary/[.07] px-3 py-2 text-xs"><span className="min-w-0 truncate text-muted-foreground">Replying to <strong className="text-foreground">{replyTo.sender.displayName}</strong>: {replyTo.body || "Attachment"}</span><button type="button" onClick={onCancelReply} aria-label="Cancel reply" className="ml-3 text-muted-foreground hover:text-foreground"><X size={14} /></button></div>}{file && <div className="mt-2 flex items-center gap-2 px-2 text-xs text-muted-foreground"><FileUp size={13} /> <span className="min-w-0 truncate">{file.name}</span><button type="button" onClick={() => setFile(null)} aria-label="Remove attachment"><X size={13} /></button></div>}<p className="mt-2 px-1 text-[10px] text-muted-foreground">Messages are protected by your account session. Attachments are validated before upload.</p></form>;
}

function NewConversation({ onClose, onCreated }: { onClose: () => void; onCreated: (id: string) => void }) {
  const [mode, setMode] = useState<"direct" | "group">("direct");
  const [username, setUsername] = useState("");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [members, setMembers] = useState("");
  const direct = trpc.messages.startDirect.useMutation({ onSuccess: result => onCreated(result.publicId), onError: error => toast.error(error.message) });
  const group = trpc.messages.createGroup.useMutation({ onSuccess: result => onCreated(result.publicId), onError: error => toast.error(error.message) });
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (mode === "direct") direct.mutate({ username }); else group.mutate({ title, description: description || null, usernames: members.split(",").map(item => item.trim().toLowerCase()).filter(Boolean) }); };
  const busy = direct.isPending || group.isPending;
  return <form onSubmit={submit} className="surface-panel mb-4 max-w-2xl border-primary/20 bg-primary/[.04] p-5"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Start a conversation</p><h2 className="mt-1 text-lg font-semibold">New chat</h2><p className="mt-1 text-sm text-muted-foreground">Use usernames to open a direct room or bring a group together.</p></div><Button type="button" variant="ghost" size="icon" className="rounded-full" onClick={onClose} aria-label="Close new chat"><X size={18} /></Button></div><div className="mt-4 flex gap-2"><Button type="button" size="sm" variant={mode === "direct" ? "default" : "outline"} className="rounded-full" onClick={() => setMode("direct")}>Direct chat</Button><Button type="button" size="sm" variant={mode === "group" ? "default" : "outline"} className="rounded-full" onClick={() => setMode("group")}><UsersRound size={14} />New group</Button></div>{mode === "direct" ? <Input className="mt-4 h-11 rounded-xl" value={username} onChange={event => setUsername(event.target.value.toLowerCase())} placeholder="Search by username" pattern="[a-z0-9_]{3,30}" aria-label="Person username" required /> : <div className="mt-4 grid gap-3"><Input className="h-11 rounded-xl" value={title} onChange={event => setTitle(event.target.value)} placeholder="Group name" minLength={2} maxLength={100} aria-label="Group name" required /><Input className="h-11 rounded-xl" value={description} onChange={event => setDescription(event.target.value)} placeholder="Description (optional)" maxLength={500} aria-label="Group description" /><Input className="h-11 rounded-xl" value={members} onChange={event => setMembers(event.target.value.toLowerCase())} placeholder="Member usernames, separated by commas" aria-label="Group member usernames" required /></div>}<div className="mt-5 flex justify-end"><Button type="submit" className="rounded-xl" disabled={busy}>{busy ? "Opening…" : mode === "group" ? "Create group" : "Open chat"}</Button></div></form>;
}

function conversationName(conversation: Conversation, currentUserId?: number) { if (conversation.kind === "group") return conversation.title || "Untitled group"; return conversation.members.find(member => member.userId !== currentUserId)?.profile.displayName ?? "Direct message"; }
function directPresence(conversation: Conversation, currentUserId: number) { const partner = conversation.members.find(member => member.userId !== currentUserId); if (!partner?.lastSeenAt) return "Offline"; return Date.now() - new Date(partner.lastSeenAt).getTime() < 90_000 ? "Active now" : `Last active ${new Date(partner.lastSeenAt).toLocaleString()}`; }
function formatTime(value: Date) { const date = new Date(value); const today = new Date(); if (date.toDateString() === today.toDateString()) return date.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); return date.toLocaleDateString([], { month: "short", day: "numeric" }); }
function Avatar({ name, avatarUrl }: { name: string; avatarUrl?: string | null }) { return <span className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-[13px] bg-secondary text-sm font-bold text-secondary-foreground">{avatarUrl ? <img src={avatarUrl} alt="" className="h-full w-full object-cover" /> : name.slice(0, 1).toUpperCase()}</span>; }
function ConversationSkeleton() { return <div className="space-y-2 p-2">{[0, 1, 2, 3].map(item => <div key={item} className="flex items-center gap-3 rounded-xl p-3"><span className="h-10 w-10 animate-pulse rounded-[13px] bg-muted" /><span className="flex-1 space-y-2"><span className="block h-3 w-2/3 animate-pulse rounded bg-muted" /><span className="block h-2.5 w-5/6 animate-pulse rounded bg-muted" /></span></div>)}</div>; }
