import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Bell, CheckCheck, Loader2 } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const labels: Record<string, string> = { like: "liked your post", comment: "commented on your post", follow: "started following you", follow_request: "requested to follow you", follow_approved: "approved your follow request", story_reply: "replied to your story", message: "sent you a message", mention: "mentioned you", group_invite: "invited you to a group", system: "sent you an update" };
export default function Notifications() { const { isAuthenticated } = useAuth(); const list = trpc.notifications.list.useQuery(undefined, { enabled: isAuthenticated, refetchInterval: 8000 }); const markAll = trpc.notifications.markAllRead.useMutation({ onSuccess: () => list.refetch() }); const mark = trpc.notifications.markRead.useMutation({ onSuccess: () => list.refetch() }); if (!isAuthenticated) return <AppShell><section className="surface-panel mx-auto max-w-lg px-6 py-14 text-center"><Bell className="mx-auto text-primary" /><h1 className="mt-5 text-2xl font-semibold">Your activity, in one place.</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Sign in to see messages, follows, reactions, mentions, invitations, and system updates.</p><Button className="mt-6 rounded-full" onClick={startLogin}>Sign in</Button></section></AppShell>; const items = list.data ?? []; return <AppShell><section className="mx-auto max-w-2xl"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Your activity</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">The moments that reached you.</h1></div><Button variant="outline" className="rounded-full" disabled={!items.some(item => !item.notification.readAt) || markAll.isPending} onClick={() => markAll.mutate()}><CheckCheck size={16} />Mark all read</Button></div><PushSetup /><div className="surface-panel mt-5 divide-y divide-border">{list.isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="animate-spin text-primary" /></div> : items.length ? items.map(({ notification, actor }) => { const href = notification.entityType === "post" ? `/post/${notification.entityPublicId}` : notification.entityType === "conversation" ? "/messages" : actor ? `/u/${actor.username}` : "/"; return <Link key={notification.publicId} href={href} onClick={() => !notification.readAt && mark.mutate({ ids: [notification.publicId] })} className={`flex gap-3 px-5 py-4 transition hover:bg-muted/55 ${notification.readAt ? "" : "bg-primary/[0.035]"}`}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[13px] bg-secondary text-sm font-bold text-secondary-foreground">{actor?.displayName.slice(0, 1).toUpperCase() ?? "L"}</span><span className="min-w-0 flex-1"><span className="text-sm"><strong>{actor?.displayName ?? "Luma"}</strong> {labels[notification.kind] ?? "sent an update"}</span><span className="mt-1 block text-xs text-muted-foreground">{new Date(notification.createdAt).toLocaleString()}</span></span>{!notification.readAt && <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-primary" />}</Link>; }) : <div className="px-6 py-14 text-center"><Bell className="mx-auto text-primary" /><h2 className="mt-4 font-semibold">You are all caught up.</h2><p className="mt-2 text-sm text-muted-foreground">New activity will appear here when it arrives.</p></div>}</div></section></AppShell>; }
function PushSetup() { const register = trpc.notifications.registerDevice.useMutation(); const [state, setState] = useState(typeof Notification === "undefined" ? "unsupported" : Notification.permission); const enable = async () => { if (!("serviceWorker" in navigator) || !("Notification" in window)) return; const permission = await Notification.requestPermission(); setState(permission); if (permission === "granted") { const registration = await navigator.serviceWorker.ready; const subscription = await registration.pushManager.getSubscription(); register.mutate({ deviceId: localStorage.getItem("luma-device-id") || (() => { const id = crypto.randomUUID(); localStorage.setItem("luma-device-id", id); return id; })(), platform: navigator.platform, pushEndpoint: subscription?.endpoint ?? null, pushSubscription: subscription ? subscription.toJSON() as Record<string, unknown> : null }); } }; if (state === "unsupported") return null; return <div className="surface-panel mt-5 flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><p className="text-sm font-semibold">Browser alerts</p><p className="mt-1 text-xs text-muted-foreground">Receive notices when a compatible push provider is configured.</p></div><Button size="sm" variant="outline" className="rounded-full" disabled={state === "granted" || register.isPending} onClick={enable}>{state === "granted" ? "Alerts enabled" : "Enable alerts"}</Button></div>; }
