import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { AlertTriangle, ArrowRight, BookOpen, CalendarClock, Check, CheckCircle2, Circle, FileText, LayoutDashboard, Plus, ShieldCheck, Sparkles, Target, Trash2, WalletCards } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

type Task = { id: string; title: string; area: "life" | "study"; due: string; done: boolean };
const starterTasks: Task[] = [
  { id: "welcome-life", title: "Add your first bill or renewal", area: "life", due: "Today", done: false },
  { id: "welcome-study", title: "Set one study goal for this week", area: "study", due: "This week", done: false },
  { id: "welcome-doc", title: "Save an important document reminder", area: "life", due: "This week", done: false },
];

export default function NuvoraDashboard() {
  const { isAuthenticated, loading } = useAuth();
  const account = trpc.account.me.useQuery(undefined, { enabled: isAuthenticated });
  const [tasks, setTasks] = useState<Task[]>(() => { try { return JSON.parse(localStorage.getItem("nuvora1-tasks") || "null") || starterTasks; } catch { return starterTasks; } });
  const [newTask, setNewTask] = useState("");
  const [scanText, setScanText] = useState("");
  const [scanResult, setScanResult] = useState<"safe" | "review" | null>(null);
  useEffect(() => { localStorage.setItem("nuvora1-tasks", JSON.stringify(tasks)); }, [tasks]);
  const completed = tasks.filter(task => task.done).length;
  const dueSoon = tasks.filter(task => !task.done).length;
  const firstName = account.data?.profile.displayName?.split(" ")[0] || account.data?.user.name?.split(" ")[0] || "there";
  const [location] = useLocation();
  const greeting = useMemo(() => { const hour = new Date().getHours(); return hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening"; }, []);
  if (location === "/life" || location === "/study" || location === "/shield") return <FocusedModule module={location.slice(1) as "life" | "study" | "shield"} firstName={firstName} />;
  if (loading || (isAuthenticated && account.isLoading)) return <AppShell><div className="grid min-h-[65vh] place-items-center text-sm text-muted-foreground">Preparing your private workspace…</div></AppShell>;
  if (!isAuthenticated) return <Welcome />;
  const addTask = (event: React.FormEvent) => { event.preventDefault(); const title = newTask.trim(); if (!title) return; setTasks(current => [{ id: crypto.randomUUID(), title, area: "life", due: "Today", done: false }, ...current]); setNewTask(""); };
  return <AppShell>
    <div className="mx-auto max-w-6xl space-y-7">
      <section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Your private command centre</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] sm:text-4xl">{greeting}, {firstName}.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Keep the important parts of life moving—without opening five different apps.</p></div><Link href="/settings"><Button variant="outline" className="w-fit rounded-full"><Sparkles size={16} /> Personalise Nuvora</Button></Link></section>
      <section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="relative overflow-hidden rounded-[1.7rem] bg-[linear-gradient(120deg,#0c2850,#075d6a_60%,#11a88f)] p-6 text-white shadow-[0_20px_55px_rgba(7,93,106,.22)] sm:p-8"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full border border-white/15" /><div className="absolute -bottom-28 right-20 h-72 w-72 rounded-full border border-white/10" /><div className="relative"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-semibold"><ShieldCheck size={14} /> NUVORA 1 workspace</span><h2 className="mt-6 max-w-lg text-2xl font-semibold tracking-[-.04em] sm:text-3xl">One calm place for your next step.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-white/75">Plan what matters, protect yourself online, and make steady progress in your studies.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="#quick-add"><Button className="rounded-full bg-white text-[#0c3653] hover:bg-white/90">Add a reminder <Plus size={16} /></Button></Link><Link href="/shield"><Button variant="ghost" className="rounded-full text-white hover:bg-white/10 hover:text-white">Check something <ArrowRight size={16} /></Button></Link></div></div></div><div className="surface-panel flex flex-col justify-between p-6"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold">Today at a glance</p><p className="mt-1 text-xs text-muted-foreground">Small steps compound.</p></div><span className="grid h-10 w-10 place-items-center rounded-2xl bg-primary/10 text-primary"><Target size={19} /></span></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted/60 p-3"><p className="text-2xl font-semibold">{dueSoon}</p><p className="mt-1 text-xs text-muted-foreground">Open items</p></div><div className="rounded-2xl bg-muted/60 p-3"><p className="text-2xl font-semibold">{completed}</p><p className="mt-1 text-xs text-muted-foreground">Completed</p></div></div></div></section>
      <section className="grid gap-4 md:grid-cols-3"><ModuleCard href="/life" icon={<WalletCards />} label="Life" title="Stay ahead" text="Bills, renewals, documents, and everyday reminders." tone="teal" /><ModuleCard href="/study" icon={<BookOpen />} label="Study" title="Make progress" text="Goals, research deadlines, notes, and applications." tone="amber" /><ModuleCard href="/shield" icon={<ShieldCheck />} label="Shield" title="Pause before you trust" text="Review suspicious links, messages, and payment requests." tone="blue" /></section>
      <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div id="life" className="surface-panel p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Life</p><h2 className="mt-1 text-xl font-semibold">Your next actions</h2></div><CalendarClock className="text-primary" size={20} /></div><div className="mt-5 space-y-2">{tasks.filter(task => task.area === "life").map(task => <TaskRow key={task.id} task={task} onToggle={() => setTasks(current => current.map(item => item.id === task.id ? { ...item, done: !item.done } : item))} onDelete={() => setTasks(current => current.filter(item => item.id !== task.id))} />)} </div><form id="quick-add" onSubmit={addTask} className="mt-5 flex gap-2"><Input value={newTask} onChange={event => setNewTask(event.target.value)} placeholder="Add a reminder…" aria-label="New reminder" /><Button type="submit" size="icon" className="shrink-0 rounded-xl" aria-label="Add reminder"><Plus size={18} /></Button></form></div><div id="study" className="surface-panel p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Study</p><h2 className="mt-1 text-xl font-semibold">Focus board</h2></div><BookOpen className="text-amber-600" size={20} /></div><div className="mt-5 rounded-2xl bg-amber-50 p-4 dark:bg-amber-950/25"><p className="text-sm font-semibold">This week’s goal</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Create a focused study target and break it into a first 25-minute session.</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-amber-200/70 dark:bg-amber-900"><div className="h-full w-1/3 rounded-full bg-amber-500" /></div><p className="mt-2 text-xs text-muted-foreground">1 of 3 steps planned</p></div><div className="mt-4 space-y-2">{tasks.filter(task => task.area === "study").map(task => <TaskRow key={task.id} task={task} onToggle={() => setTasks(current => current.map(item => item.id === task.id ? { ...item, done: !item.done } : item))} onDelete={() => setTasks(current => current.filter(item => item.id !== task.id))} />)}</div><Link href="#quick-add" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-primary">Add a study task <ArrowRight size={15} /></Link></div></section>
      <section className="surface-panel p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Shield</p><h2 className="mt-1 text-xl font-semibold">Quick safety check</h2><p className="mt-1 text-sm text-muted-foreground">Paste a suspicious link or message. Nuvora highlights common warning signs.</p></div><Link href="/shield" className="text-sm font-semibold text-primary">Open full Shield <ArrowRight className="ml-1 inline" size={15} /></Link></div><form className="mt-5 flex flex-col gap-2 sm:flex-row" onSubmit={event => { event.preventDefault(); const suspicious = /password|urgent|verify|payment|gift|prize|crypto|otp/i.test(scanText); setScanResult(suspicious ? "review" : "safe"); }}><Input value={scanText} onChange={event => { setScanText(event.target.value); setScanResult(null); }} placeholder="Paste a link or message to review…" aria-label="Text to scan" /><Button type="submit" className="rounded-xl sm:w-auto">Check now <ShieldCheck size={16} /></Button></form>{scanResult && <div className={`mt-3 flex items-start gap-3 rounded-2xl p-4 text-sm ${scanResult === "review" ? "bg-amber-50 text-amber-900 dark:bg-amber-950/25 dark:text-amber-100" : "bg-emerald-50 text-emerald-900 dark:bg-emerald-950/25 dark:text-emerald-100"}`}>{scanResult === "review" ? <AlertTriangle size={18} className="mt-0.5 shrink-0" /> : <CheckCircle2 size={18} className="mt-0.5 shrink-0" />}<span><strong>{scanResult === "review" ? "Review before acting." : "No common warning signs found."}</strong><br /><span className="opacity-75">This is an early warning tool, not a guarantee that content is safe.</span></span></div>}</section>
    </div>
  </AppShell>;
}
function FocusedModule({ module, firstName }: { module: "life" | "study" | "shield"; firstName: string }) {
  const [items, setItems] = useState<Task[]>(() => { try { return JSON.parse(localStorage.getItem(`nuvora1-${module}-items`) || "[]"); } catch { return []; } });
  const [value, setValue] = useState("");
  const [scanResult, setScanResult] = useState<"safe" | "review" | null>(null);
  useEffect(() => { localStorage.setItem(`nuvora1-${module}-items`, JSON.stringify(items)); }, [items, module]);
  const add = (event: React.FormEvent) => { event.preventDefault(); const title = value.trim(); if (!title) return; setItems(current => [{ id: crypto.randomUUID(), title, area: module === "study" ? "study" : "life", due: "Today", done: false }, ...current]); setValue(""); };
  if (module === "shield") return <AppShell><div className="mx-auto max-w-4xl space-y-7"><BackLink /><section><p className="eyebrow">Shield workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] sm:text-4xl">Pause before you trust.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Review suspicious links, messages, QR text, or payment requests before you click or send money.</p></section><section className="surface-panel p-5 sm:p-7"><form onSubmit={event => { event.preventDefault(); const suspicious = /password|urgent|verify|payment|gift|prize|crypto|otp|refund/i.test(value); setScanResult(suspicious ? "review" : "safe"); }}><label className="text-sm font-semibold" htmlFor="shield-input">Paste something to review</label><textarea id="shield-input" value={value} onChange={event => { setValue(event.target.value); setScanResult(null); }} className="mt-3 min-h-36 w-full resize-y rounded-2xl border border-input bg-background p-4 text-sm outline-none ring-offset-background focus-visible:ring-2 focus-visible:ring-ring" placeholder="Paste a link, message, or payment request…" /><Button type="submit" className="mt-4 rounded-xl" disabled={!value.trim()}><ShieldCheck size={17} /> Review warning signs</Button></form>{scanResult && <div className={`mt-5 rounded-2xl p-5 ${scanResult === "review" ? "bg-amber-50 dark:bg-amber-950/25" : "bg-emerald-50 dark:bg-emerald-950/25"}`}><div className="flex items-start gap-3">{scanResult === "review" ? <AlertTriangle className="text-amber-700" /> : <CheckCircle2 className="text-emerald-700" />}<div><p className="font-semibold">{scanResult === "review" ? "Review carefully before acting." : "No common warning signs found."}</p><p className="mt-1 text-sm text-muted-foreground">{scanResult === "review" ? "Urgency, payment requests, OTP requests, or prize language are common scam signals." : "This quick check cannot guarantee that content is safe. Verify through an official channel."}</p></div></div></div>}</section><div className="grid gap-4 sm:grid-cols-3"><InfoCard icon={<ShieldCheck />} title="Never share OTPs" text="Legitimate support should not ask for your one-time code." /><InfoCard icon={<AlertTriangle />} title="Slow down" text="Urgency is a common pressure tactic." /><InfoCard icon={<FileText />} title="Verify directly" text="Use the official app or website, not a message link." /></div></div></AppShell>;
  const label = module === "life" ? "Life workspace" : "Study workspace";
  const title = module === "life" ? "Stay ahead of the small things." : "Turn study time into progress.";
  const description = module === "life" ? "Keep renewals, bills, documents, and personal reminders in one calm view." : "Track research goals, deadlines, applications, and focused study actions.";
  return <AppShell><div className="mx-auto max-w-5xl space-y-7"><BackLink /><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">{label}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description} Welcome back, {firstName}.</p></div><div className="rounded-2xl bg-primary/10 px-4 py-3 text-sm font-semibold text-primary">{items.filter(item => item.done).length} complete · {items.filter(item => !item.done).length} open</div></section><section className="surface-panel p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">{module === "life" ? "Your reminders" : "Your study actions"}</p><p className="mt-1 text-xs text-muted-foreground">Add one clear next step at a time.</p></div>{module === "life" ? <CalendarClock className="text-primary" /> : <BookOpen className="text-amber-600" />}</div><div className="mt-5 space-y-2">{items.length ? items.map(item => <TaskRow key={item.id} task={item} onToggle={() => setItems(current => current.map(row => row.id === item.id ? { ...row, done: !row.done } : row))} onDelete={() => setItems(current => current.filter(row => row.id !== item.id))} />) : <div className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Nothing here yet. Add your first {module === "life" ? "reminder" : "study action"} below.</div>}</div><form onSubmit={add} className="mt-5 flex gap-2"><Input value={value} onChange={event => setValue(event.target.value)} placeholder={module === "life" ? "e.g. Renew health insurance" : "e.g. Read two research papers"} aria-label={module === "life" ? "New life reminder" : "New study action"} /><Button type="submit" className="shrink-0 rounded-xl"><Plus size={17} /> Add</Button></form></section></div></AppShell>;
}
function BackLink() { return <Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground">← Back to dashboard</Link>; }
function InfoCard({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="surface-panel p-5"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-primary/10 text-primary">{icon}</span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function TaskRow({ task, onToggle, onDelete }: { task: Task; onToggle: () => void; onDelete: () => void }) { return <div className="flex items-center gap-3 rounded-2xl border border-border/70 bg-background/50 px-3 py-3"><button type="button" onClick={onToggle} className="text-primary" aria-label={task.done ? "Mark incomplete" : "Mark complete"}>{task.done ? <CheckCircle2 size={19} /> : <Circle size={19} />}</button><span className={`min-w-0 flex-1 text-sm ${task.done ? "text-muted-foreground line-through" : "font-medium"}`}>{task.title}</span><span className="hidden text-[11px] text-muted-foreground sm:inline">{task.due}</span><button type="button" onClick={onDelete} className="text-muted-foreground hover:text-destructive" aria-label="Delete item"><Trash2 size={15} /></button></div>; }
function ModuleCard({ href, icon, label, title, text, tone }: { href: string; icon: React.ReactNode; label: string; title: string; text: string; tone: string }) { return <Link href={href} className="surface-panel group p-5 transition hover:-translate-y-0.5 hover:border-primary/40"><div className={`grid h-10 w-10 place-items-center rounded-2xl ${tone === "amber" ? "bg-amber-100 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300" : tone === "blue" ? "bg-blue-100 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300" : "bg-primary/10 text-primary"}`}>{icon}</div><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-muted-foreground">{label}</p><h3 className="mt-1 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><ArrowRight className="mt-4 text-primary transition group-hover:translate-x-1" size={17} /></Link>; }
function Welcome() { return <AppShell compact><div className="mx-auto grid min-h-[calc(100dvh-8rem)] max-w-6xl items-center gap-12 py-8 lg:grid-cols-[1.08fr_.92fr]"><section className="max-w-xl"><p className="eyebrow">NUVORA 1 · private life OS</p><h1 className="mt-5 text-5xl font-semibold leading-[1.02] tracking-[-.07em] sm:text-6xl">Move through life with <span className="text-primary">more clarity.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-muted-foreground">A calm personal workspace for life reminders, higher-study progress, and safer digital decisions.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup"><Button className="h-12 rounded-xl px-5 text-base">Start with Nuvora <ArrowRight size={17} /></Button></Link><Link href="/login"><Button variant="outline" className="h-12 rounded-xl px-5 text-base">Sign in</Button></Link></div><div className="mt-8 grid max-w-lg grid-cols-3 gap-3 text-xs text-muted-foreground"><span><Check className="mb-2 text-primary" size={16} />Private by default</span><span><Check className="mb-2 text-primary" size={16} />Free core tools</span><span><Check className="mb-2 text-primary" size={16} />Built for focus</span></div></section><div className="relative"><div className="absolute -inset-8 rounded-full bg-primary/15 blur-3xl" /><div className="surface-panel relative p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="eyebrow">Your day, simplified</p><p className="mt-1 text-xl font-semibold">A quieter dashboard</p></div><LayoutDashboard className="text-primary" /></div><div className="mt-6 space-y-3"><Preview icon={<WalletCards />} title="Life reminders" detail="2 renewals coming up" /><Preview icon={<BookOpen />} title="Study focus" detail="25 minutes planned" /><Preview icon={<ShieldCheck />} title="Digital safety" detail="Pause before you trust" /></div><div className="mt-5 rounded-2xl bg-muted p-4"><p className="text-xs font-semibold text-muted-foreground">NUVORA 1</p><p className="mt-2 text-sm font-medium">Organize. Progress. Protect.</p></div></div></div></div></AppShell>; }
function Preview({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-border/70 bg-card p-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary">{icon}</span><span className="min-w-0 flex-1"><strong className="block text-sm">{title}</strong><span className="text-xs text-muted-foreground">{detail}</span></span><ArrowRight size={15} className="text-muted-foreground" /></div>; }
