import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ChevronLeft, ChevronRight, ImagePlus, Loader2, Plus, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";

function toBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("File could not be read.")); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.readAsDataURL(file); }); }
type StoryRow = { story: { publicId: string; kind: "image" | "video" | "audio" | "file"; url: string; textOverlay: string | null; expiresAt: Date; viewsCount: number }; author: { displayName: string; username: string; avatarUrl: string | null } };

export default function Stories() {
  const { data, isLoading, refetch } = trpc.stories.list.useQuery();
  const [active, setActive] = useState(-1);
  const [createOpen, setCreateOpen] = useState(false);
  const stories = (data ?? []) as StoryRow[];
  return <AppShell><section className="mx-auto max-w-5xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">In the moment</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Stories that disappear gracefully.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Each story belongs to a single day, with clear audience controls and a simple, immersive viewer.</p></div><Button onClick={() => setCreateOpen(true)} className="rounded-full"><Plus size={16} />Add a story</Button></div>{createOpen && <StoryComposer onClose={() => setCreateOpen(false)} onCreated={() => { setCreateOpen(false); refetch(); }} />}{isLoading ? <div className="grid min-h-70 place-items-center"><Loader2 className="animate-spin text-primary" /></div> : stories.length ? <><div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{stories.map((row, index) => <button type="button" key={row.story.publicId} onClick={() => setActive(index)} className="group text-left"><div className="relative aspect-[3/4] overflow-hidden rounded-[1.35rem] bg-secondary ring-2 ring-primary/40 transition group-hover:-translate-y-1 group-hover:ring-primary"><StoryVisual story={row.story} /></div><p className="mt-2 truncate text-sm font-semibold">{row.author.displayName}</p><p className="truncate text-xs text-muted-foreground">@{row.author.username}</p></button>)}</div><StoryViewer items={stories} index={active} onClose={() => setActive(-1)} onChange={setActive} /></> : <section className="surface-panel mt-8 px-6 py-14 text-center"><ImagePlus className="mx-auto text-primary" /><h2 className="mt-4 text-xl font-semibold">Nothing to catch up on yet.</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-muted-foreground">Stories from people you follow will collect here for their 24-hour window.</p></section>}</section></AppShell>;
}

function StoryComposer({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const [file, setFile] = useState<File | null>(null); const [textOverlay, setTextOverlay] = useState(""); const [visibility, setVisibility] = useState<"everyone" | "followers" | "none">("everyone"); const fileInput = useRef<HTMLInputElement>(null);
  const upload = trpc.uploads.create.useMutation(); const create = trpc.stories.create.useMutation(); const busy = upload.isPending || create.isPending;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!file) return toast.error("Choose an image or video for your story."); try { const asset = await upload.mutateAsync({ purpose: "story", originalName: file.name, mimeType: file.type, dataBase64: await toBase64(file) }); await create.mutateAsync({ uploadId: asset.publicId, textOverlay: textOverlay || null, visibility }); toast.success("Story shared for the next 24 hours."); onCreated(); } catch (error) { toast.error(error instanceof Error ? error.message : "The story could not be shared."); } };
  return <form onSubmit={submit} className="surface-panel mt-6 p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Share a story</h2><p className="mt-1 text-sm text-muted-foreground">It will expire automatically after 24 hours.</p></div><Button type="button" variant="ghost" size="icon" className="rounded-full" onClick={onClose}><X size={18} /></Button></div><div className="mt-5 flex flex-wrap gap-3"><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" className="sr-only" onChange={event => setFile(event.target.files?.[0] ?? null)} /><Button type="button" variant="outline" className="rounded-full" onClick={() => fileInput.current?.click()}><ImagePlus size={16} />{file ? file.name.slice(0, 28) : "Choose image or video"}</Button><select aria-label="Story visibility" value={visibility} onChange={event => setVisibility(event.target.value as typeof visibility)} className="h-10 rounded-full border border-border bg-card px-4 text-sm"><option value="everyone">Everyone</option><option value="followers">Followers</option><option value="none">Only me</option></select></div><Input className="mt-4" value={textOverlay} onChange={event => setTextOverlay(event.target.value)} maxLength={500} placeholder="Add a thought (optional)" /><div className="mt-5 flex justify-end"><Button type="submit" className="rounded-full" disabled={busy}>{busy && <Loader2 className="animate-spin" size={16} />}{busy ? "Sharing…" : "Share story"}</Button></div></form>;
}

function StoryViewer({ items, index, onClose, onChange }: { items: StoryRow[]; index: number; onClose: () => void; onChange: (index: number) => void }) {
  const row = items[index]; const view = trpc.stories.recordView.useMutation();
  useEffect(() => { if (index < 0 || !row) return; view.mutate({ storyId: row.story.publicId }); const timer = window.setTimeout(() => { if (index < items.length - 1) onChange(index + 1); else onClose(); }, 6000); return () => window.clearTimeout(timer); }, [index, row?.story.publicId]);
  if (index < 0 || !row) return null;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/90 p-4" role="dialog" aria-modal="true" aria-label="Story viewer"><div className="relative h-[min(78vh,760px)] w-[min(95vw,430px)] overflow-hidden rounded-[2rem] bg-zinc-900 shadow-2xl"><div className="absolute inset-x-5 top-4 z-10 h-1 overflow-hidden rounded-full bg-white/30"><div key={row.story.publicId} className="h-full origin-left animate-[story_6s_linear_forwards] bg-white" /></div><button type="button" className="absolute right-4 top-7 z-10 grid h-9 w-9 place-items-center rounded-full bg-black/30 text-white" onClick={onClose} aria-label="Close story"><X size={19} /></button><StoryVisual story={row.story} className="h-full" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent px-6 pb-6 pt-20 text-white"><p className="font-semibold">{row.author.displayName}</p><p className="mt-1 text-sm text-white/75">@{row.author.username}</p>{row.story.textOverlay && <p className="mt-4 text-base font-medium leading-6">{row.story.textOverlay}</p>}</div><button type="button" className="absolute inset-y-0 left-0 w-1/3" aria-label="Previous story" onClick={() => index > 0 && onChange(index - 1)}><ChevronLeft className="mx-3 text-white/80" /></button><button type="button" className="absolute inset-y-0 right-0 w-1/3" aria-label="Next story" onClick={() => index < items.length - 1 ? onChange(index + 1) : onClose()}><ChevronRight className="ml-auto mr-3 text-white/80" /></button></div></div>;
}
function StoryVisual({ story, className = "" }: { story: StoryRow["story"]; className?: string }) { return story.kind === "video" ? <video src={story.url} className={`h-full w-full object-cover ${className}`} autoPlay muted playsInline controls /> : <img src={story.url} alt={story.textOverlay ?? "Story"} className={`h-full w-full object-cover ${className}`} />; }
