import { useEffect, useState, type ReactNode } from "react";
import { Link, useLocation } from "wouter";
import { Bell, BookOpen, CircleUserRound, LayoutDashboard, Laptop, Moon, ShieldCheck, Sun, WalletCards } from "lucide-react";
import { useTheme } from "@/contexts/ThemeContext";

const navigation = [
  { href: "/", label: "Home", icon: LayoutDashboard },
  { href: "/life", label: "Life", icon: WalletCards },
  { href: "/study", label: "Study", icon: BookOpen },
  { href: "/shield", label: "Shield", icon: ShieldCheck },
];
function ThemeToggle() { const { theme, setTheme } = useTheme(); return <div className="flex rounded-full bg-muted p-1" role="group" aria-label="Color theme"><button type="button" onClick={() => setTheme?.("light")} className={`grid h-8 w-8 place-items-center rounded-full ${theme === "light" ? "bg-card text-foreground shadow-sm" : "text-muted-foreground"}`} aria-label="Use light theme"><Sun size={15} /></button><button type="button" onClick={() => setTheme?.("system")} className={`grid h-8 w-8 place-items-center rounded-full ${theme === "system" ? "bg-card text-foreground shadow-sm" : "text-muted-foreground"}`} aria-label="Use system theme"><Laptop size={15} /></button><button type="button" onClick={() => setTheme?.("dark")} className={`grid h-8 w-8 place-items-center rounded-full ${theme === "dark" ? "bg-card text-foreground shadow-sm" : "text-muted-foreground"}`} aria-label="Use dark theme"><Moon size={15} /></button></div>; }
type InstallPromptEvent = Event & { prompt: () => Promise<void> };
function InstallButton() { const [prompt, setPrompt] = useState<InstallPromptEvent | null>(null); useEffect(() => { const capture = (event: Event) => { event.preventDefault(); setPrompt(event as InstallPromptEvent); }; window.addEventListener("beforeinstallprompt", capture); return () => window.removeEventListener("beforeinstallprompt", capture); }, []); if (!prompt) return null; return <button type="button" className="rounded-full border border-border bg-card px-3 py-2 text-xs font-semibold text-muted-foreground hover:bg-accent hover:text-foreground" onClick={async () => { await prompt.prompt(); setPrompt(null); }}>Install app</button>; }
export function AppShell({ children, compact = false }: { children: ReactNode; compact?: boolean }) { const [location] = useLocation(); const active = (href: string) => href === "/" ? location === "/" : location.startsWith(href); return <div className="relative isolate min-h-dvh bg-transparent text-foreground"><header className="sticky top-0 z-30 border-b border-border/80 bg-background/88 backdrop-blur-xl"><div className="mx-auto flex h-[4.5rem] max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/" className="flex items-center gap-2.5" aria-label="NUVORA 1 home"><img src="/nuvora1-logo.png" alt="NUVORA 1" className="h-9 w-auto max-w-[9rem] object-contain object-left" /></Link>{!compact && <nav className="hidden items-center gap-1 lg:flex" aria-label="Main navigation">{navigation.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`flex items-center gap-2 rounded-xl px-3.5 py-2 text-sm font-semibold transition ${active(href) ? "bg-primary/10 text-primary" : "text-muted-foreground hover:bg-accent hover:text-foreground"}`}><Icon size={16} />{label}</Link>)}</nav>}<div className="flex items-center gap-1.5"><InstallButton />{!compact && <Link href="/notifications" className="hidden h-9 w-9 place-items-center rounded-full text-muted-foreground hover:bg-accent hover:text-foreground sm:grid" aria-label="Open notifications"><Bell size={18} /></Link>}<div className="hidden sm:block"><ThemeToggle /></div><Link href="/accounts" className="grid h-9 w-9 place-items-center rounded-full border border-border bg-card text-muted-foreground hover:border-primary/40 hover:text-foreground" aria-label="Open account center"><CircleUserRound size={17} /></Link></div></div></header><main className="mx-auto w-full max-w-7xl px-4 pb-24 pt-5 sm:px-6 sm:pt-8 lg:px-8">{children}</main>{!compact && <nav className="fixed inset-x-0 bottom-0 z-30 border-t border-border/80 bg-background/95 px-2 pb-[max(0.4rem,env(safe-area-inset-bottom))] pt-1.5 backdrop-blur-xl lg:hidden" aria-label="Mobile navigation"><div className="mx-auto grid max-w-lg grid-cols-4 items-center gap-1">{navigation.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`flex min-w-0 flex-col items-center gap-1 rounded-xl px-1 py-2 text-[10px] font-semibold ${active(href) ? "text-primary" : "text-muted-foreground"}`} aria-current={active(href) ? "page" : undefined}><Icon size={19} strokeWidth={active(href) ? 2.5 : 2} /><span className="truncate">{label}</span></Link>)}</div></nav>}</div>; }
